### ISSUE TITLE
Trying to use pattern.nlp in Rstudio 3.5.1 - text mining

### ISSUE THREAD

**Issue by shashankgjoshi** [jwijffels/ceta-txtmining#2]
I am trying to replicate the CETA code in Rsutdio 3.5.1 but am getting an error for pattern.nlp package. It does not recognize it. pattern_pos function cannot be used. When I searched CRAN repositories patternator, patternclass and patternplot are available.

Is there a different way of installing this code when changes using pattern.nlp class?

**Comment by jwijffels** [comment]
No, there is not. pattern.nlp is available at https://github.com/bnosac/pattern.nlp, it is not available on CRAN.
If advise you to use the udpipe R package. It provides you anything you need regarding text mining. That package is on CRAN: https://CRAN.R-project.org/package=udpipe

**Comment by shashankgjoshi** [comment]
thanks. Just tried to install udpipe in R studio. it say package not available.

**Comment by jwijffels** [comment]
udpipe is on CRAN:  https://CRAN.R-project.org/package=udpipe

**Comment by shashankgjoshi** [comment]
Yes...I saw it but sorry am trying to install something out of R studio for the first time...how do i get it into R studio? thanks

**Comment by shashankgjoshi** [comment]
Done. thanks.
